### ISSUE TITLE
Handling of characterwise visual selection and TCommentInline

### ISSUE THREAD

**Issue by blueyed** [tomtom/tcomment_vim#143]
I've tried to use `:TCommentInline` on a characterwise visual selection.

Given the following Lua code:

    awful.key({ "Shift", modkey }, "a", function()
      shift_insert_pressed = true
      bnote("pressed")
    end, function()

1. When I visually select from `function` to `end`, `<Leader>_i` (`:TCommentInline`) does nothing.

2. When I visually select from the `awful.key` to `end`, it results in this:

    --[[awf --]]ul.key({ "Shift", modkey }, "a", function()
    --[[  s --]]hift_insert_pressed = true
    --[[  b --]]note("pressed")
    --[[end --]], function()

It seems to assume a visual _block_ selection here?

In both cases I would have expected it to surround the visual selection using `--[[ ` and ` --]]`.

**Comment by tomtom** [comment]
> In both cases I would have expected it to surround the visual 
> selection using |--[[| and |--]]|. 
"inline" comments are striclty comments within a line. What you want, 
most likely is a block comment (a multi-line comment with a single start 
and end comment marker) but tcoment supports block comments only for 
whole lines.

tcomment doesn't support a way to comment out function()...end as 
formatted in your example. You'd have to reformat the code so that you 
can comment out whole lines.

**Comment by Aster89** [comment]
Well, the nice thing would have been to add support for this sort of commenting, because it's useful in most languages where you can put line breaks just about everywhere, including C, C++, D, C#, F#, Rust, Haskell, Scheme and other LISPs, Java, JavaScript, TypeScript, OCaml, Lua, Clojure, ... you name it.

**Comment by tomtom** [comment]
Inline comments (if the filetype supports it) are for comments within a line.
Mutiline inline comments is something you should not do - IMHO YMMV etc. Just because a language definition supports it doesn't mean it's a good idea.
