### ISSUE TITLE
Make license permissive?

### ISSUE THREAD

**Issue by tony** [tomtom/tcomment_vim#192]
https://github.com/tomtom/tcomment_vim/blob/master/LICENSE.TXT

GPLv3 could cause config files using tcomment_vim to become a derivative of tcomment_vim.

I don't think that's the intention of the authors/contributors.

**Comment by tomtom** [comment]
> GPLv3 could cause config files using tcomment_vim to become a 
derivitive of tcomment_vim.

Could you please substantiate this claim. I don't think emacs elisp 
configuration file automatically becomes a derivative of emacs. If it 
were so, you wouldn't have to sign an extra agreement with the FSF when 
contributing to emacs, would you -- I assume emacs is published under 
the GPL3.

**Comment by tony** [comment]
The ambiguity of the wording of what could allegedly a derivative in (L)GPL2/3 is why I don't want to mix viral code in my stuff. In other circumstances it's beyond my control due to work. You picked the license, so you're aware that it's yet to be tested in such a circumstance. Has their been any lawsuits related to GPL version 3 licenses with vim script, or any other scripting languages that you've seen?

I also I don't use emacs, so can't speak on it. Emacs is a program that evaluates the config. Tcomment isn't vim.

The other thing is code and libraries are different than a binary application that could be GPL evaluating a config.

And also, the (L)GPL doesn't really work well with the realities of scripting languages.

> GPLv3 could cause config files using tcomment_vim to become a derivitive of tcomment_vim.

I license my vim config under a permissive license. I don't want to incorporate GPL code since it's not compatible. I don't want my downstream users copying into GPL'd code accidentally.

There's many ways a derivative could be alleged, due to the vague wording, it being a scripting language, etc. The allegation of it is enough to bankrupt someone in court costs.

But for me it's about keeping viral code out of my work areas.

> Could you please substantiate this claim.

I don't really have the energy to debate licenses, but I think it'd be better to look at it the other way around: If you're adding legal clauses to a license, can you explain each clause in your license and why your plugin needs it?

**Comment by tony** [comment]
I notice you're using email, please see https://github.com/tomtom/tcomment_vim/issues/192#issuecomment-336212652 because I made edits.

**Comment by tomtom** [comment]
The plugin provides ways to configure how it works via global variables. As such, your configuration is data and not code. Also, as your configuration isn't needed to run the plugin and as it doesn't (usually) change how the plugin works, it isn't IMHO part of the plugin or a derivative work.

If you patched certain functions, this could be a slightly different story though and one should discuss whether the changes are worthwhile being included in the main version of the plugin. But even then I don't think it counts as derivative work since the configuration doesn't run without the main source code. So unless you distribute a patched version of the plugin under a conflicting license, I personally don't see a problem. But yes, if you actually distributed a patched / improved version of the plugin, I would actually want demand from you to make the source code publicly available under the same license. I wouldn't want plugins derived from my work become non-free code. (However this should ever happen.)

**Comment by tony** [comment]
>  I wouldn't want plugins derived from my work become non-free. (However this should ever happen.)

That's the issue. I don't think a vim plugin is likely to become cannibalized or forked into something else, so I feel the terms of the GPL aren't proportional.

The other thing is I have larger projects that are MIT/BSD licensed, and no one has forked them, to my knowledge, into non-free things. Though if they did, they're incurring expense by maintaining a fork and not giving contributions back upstream to me.

**Comment by tomtom** [comment]
I'm not a lawyer but I tend to say being viral is a good thing wrt free software. I personally don't fully understand and follow your arguments though. Unless you provide new evidence (e.g. a reference to a more detailled discussion of this issue where the case of a plugin being licensed under the GPL is being discussed), I'd say case closed. IMHO one could probably call into question whether one can license a plugin under the GPL when the main software package is not. Anyway, I rather think this is a rather esoteric discussion.

**Comment by tony** [comment]
> Anyway, I rather think this is a rather esoteric discussion.

It's fine, I'll stop using your plugin. Heh.

Can't say I didn't try to explain.
