### ISSUE TITLE
Can't uncomment HTML in JSX files

### ISSUE THREAD

**Issue by kkoomen** [tomtom/tcomment_vim#248]
No matter which keystroke I use, I can't uncomment HTML in JSX files.

![tcomment-jsx-uncomment-bug](https://user-images.githubusercontent.com/10693490/54459142-12410c80-4766-11e9-8ff0-4db5b4d2bfcd.gif)

**Comment by tomtom** [comment]
Could you please tell me, at each step, the result of `:call tcomment#debug#CollectInfo()` at the beginning of the line in question. Thanks.

**Comment by kkoomen** [comment]
`|` = cursor

Scenario
```javascript
import React, { Component } from 'react';

class Test extends Component {
  render() {
    return (
      |<div className="Test" />
    );
  }
}

export default Test;
```

Debug
```
TCOMMENT: &ft = javascript.jsx
TCOMMENT: ft  = javascript.jsx
TCOMMENT: stx = jsx
TCOMMENT: ct  = {'commentstring': '{/* %s */}', 'mode': '', 'filetype': 'jsx'}
```

<hr />


Scenario (pressed `gcc`)
```javascript
import React, { Component } from 'react';

class Test extends Component {
  render() {
    return (
      |{/* <div className="Test" /> */}
    );
  }
}

export default Test;

```

Debug
```

TCOMMENT: &ft = javascript.jsx
TCOMMENT: ft  = javascript.jsx
TCOMMENT: stx = javascriptObjectBraces
TCOMMENT: ct  = {'rxmid': '', 'rxend': '', 'commentstring': '// %s', 'commentstring_rx': '\%%(// %s\|/* %s */\)', 'mode': '', 'filetype': 'javascript', 'replacements': {'*/': {'subst': '|)}>#', 'guard_rx': '^\s*/\?\*'}, '/*': {'subst': '#<{(|', 'guard_rx': '^\s*/\?\*'}}, 'rxbeg': '\*\+'}
```

I think this should already give you enough information.

**Comment by tomtom** [comment]
So the braces are recognized as javascript braces which is why it uses 
the wrong comment definition. This is a weird special case. I don't know 
yet how, if at all, tcomment should handle this. IMHO it would be better 
to adapt the jsx syntax definition to highlight {/* ... */} as comment 
but I don't know jsx and I cannot tell if this would make sense.

**Comment by tomtom** [comment]
BTW what software did you use to create the screencast?

**Comment by kkoomen** [comment]
@tomtom It does makes sense, but here's the thing: JSX should use {/* ... /*} only when the cursor is in or surrounded by HTML. Will you fix this? Because you closed this issue without reason.

<hr />

I used Kap to record a part of the screen.

**Comment by tomtom** [comment]
I closed the issue because the latest commit should fix the uncommenting 
issue, doesn't it. It's beyond the scope of tcomment to check the 
context (previous syntax name) of a syntax. This should be done in the 
syntax vim file that should assign a different syntax name to braces 
within html comments. vim's syntax definitions provide a way to define 
hierachies of syntax groups (i.e. one group following another), tcomment 
does not.

**Comment by kkoomen** [comment]
@tomtom I pulled from master and this is indeed fixed. Thanks!

**Comment by alextes** [comment]
@tomtom thanks for another improvement!
This has been bugging me since you last made the improvements that made commenting work well (thanks!), which sadly revealed the uncommenting to still be troublesome. I felt guilty continuously asking for improvements, when you'd already been responsive and helpful, and decided to wait until it bugged me enough to open a PR. I see it's already picked up! Thanks for that!

Sadly, this doesn't seem to be working for me. Can we reopen?
Version is `46d8351`, which is master as of right now.
Keystrokes are: `gcc gcc g<c g<c`
Debug info for each step, starting with the state before any commenting is:
```
TCOMMENT: &ft = javascript.jsx
TCOMMENT: ft  = javascript.jsx
TCOMMENT: stx = jsx
TCOMMENT: ct  = {'commentstring': '{/* %s */}', 'commentstring_rx': '\%%(// %s\|{/* %s */}\)', 'mode': '', 'filetype': 'jsx'}
```
```
TCOMMENT: &ft = javascript.jsx
TCOMMENT: ft  = javascript.jsx
TCOMMENT: stx = javascriptBraces
TCOMMENT: ct  = {'rxmid': '', 'rxend': '', 'commentstring': '// %s', 'commentstring_rx': '\%%(// %s\|/* %s */\)', 'mode': '', 'filetype': 'javascript', 'replacements': {'*/': {'subst': '|)}>#', 'guard_rx': '^\s*/\?\*'}, '/*': {'subst': '#<{(|', 'guard_rx': '^\s*/\?\*'}}, 'rxbeg': '\*\+'}
```
```

TCOMMENT: &ft = javascript.jsx
TCOMMENT: ft  = javascript.jsx
TCOMMENT: stx = jsxRegion
TCOMMENT: ct  = {'commentstring': '{/* %s */}', 'commentstring_rx': '\%%(// %s\|{/* %s */}\)', 'mode': '', 'filetype': 'jsx'}
```
![comment-jsx-1](https://user-images.githubusercontent.com/2011351/54747108-3ff6dd00-4bce-11e9-9e12-15bac76921df.gif)
Same for tsx files.

**Comment by alextes** [comment]
@kkoomen this Kap thing is neat by the way. If I can ever offer you a hot thank you beverage of choice let me know!

**Comment by kkoomen** [comment]
![demo-tcomment-working](https://user-images.githubusercontent.com/10693490/54782385-10bc8c00-4c1f-11e9-98ab-9443cd9fc3de.gif)

@alextes I am on `46d8351` as well now and this is what I have ^  -- which works as expected, so re-opening is not needed I suppose. Do you have neovim?

**Comment by alextes** [comment]
@kkoomen yup, neovim, I'll try and rule out plugins.

**Comment by alextes** [comment]
`othree/yajs.vim` and `mxw/vim-jsx` together break this. Thanks for the hint kkoomen. I'll see if I can solve it. Mind telling me what you use for JSX highlighting in the meantime?

**Comment by tomtom** [comment]
Are you certain, you use the HEAD version from github?

**Comment by alextes** [comment]
Yup, certain @tomtom , but a friendly person already pointed out it's plugins interfering. To be specific `ohtree/yajs.vim` doesn't assign a jsx syntax group but a JS one. I'll link the issue from when I get around to creating it.

**Comment by kkoomen** [comment]
@alextes I had some issues once using `vim-jsx` but I am using [`vim-polyglot`](https://github.com/sheerun/vim-polyglot) these days to get a good syntax highlighting. It is an up-to-date repository. I do recommend to use this rather then scraping your own packages of the internet ;)

**Comment by andrescuco** [comment]
Recently I've come across the same issue. Except that I've tried pretty much every jsx syntax plugin and it still gives me the behavior described by OP. Using `vim-polyglot` doesn't work either. If this is an issue with the jsx syntax plugins and not related to tcomment please let me know and I'll open an issue in the correct repo. I'll post the result of `tcomment#debug#CollectInfo()` when trying to _uncomment_ JSX if it's of any help. I'm using a .js file, but the behavior using .jsx / .tsx is the same. 

```
TCOMMENT: &ft = javascript => javascript
TCOMMENT: stx = jsxElement => jsxElement
TCOMMENT: ct  = {'rxmid': '', 'rxend': '', 'commentstring': '// %s', 'commentstring_rx': '\%%(// %s\|/* %s */\)', 'mode': '', 'filetype': 'javascript', 'replacements': {'*/': {'subst': '|)}>#', 'guard_rx': '^\s*/\?\*'}, '/*': {'subst': '#<{(|', 'guard_rx': '^\s*/\?\*'}}, 'rxbeg': '\*\+'}
```

**Comment by tomtom** [comment]
I'm sorry but I cannot follow the thread that closely. Could you please describe exactly what you're trying to achieve. JSX files seem to work fine with the default vim plugins. But I don't do jsx and I need some help to find out what's going wrong.

**Comment by andrescuco** [comment]
@tomtom It's the same issue with uncommenting discussed earlier (gif originally by alextes):

![comment-jsx-1](https://user-images.githubusercontent.com/2011351/54747108-3ff6dd00-4bce-11e9-9e12-15bac76921df.gif)

Here's the output of running `Tlibtraceset --file=tcomment.log +tcomment`: https://pastebin.com/pQd00zqV

As of jsx-plugins I'm using `vim-polyglot` but I've used pretty much all of jsx plugins available right now and the issue still persists.
