### ISSUE TITLE
`gcc` changed the previous visual area.

### ISSUE THREAD

**Issue by voldikss** [tomtom/tcomment_vim#270]
After using `gcc` to comment one line, the previous visual area was changed to that line(using `gv` to verify that). 

This shouldn't be expected. The plugin should keep the previous visual area.

How do you think about this? Is it easy/necessary to fix?

**Comment by tomtom** [comment]
In order to normalize the various invocation modes, 
`tcomment#operator#Op()` creates a visual area for the code that should 
be commented. This is a relic from vim5. It's possible this can be done 
better today but since this part of the code was suprisingly fragile in 
the past (working with selected text is suprisingly fragile in VIM with 
a lot of border cases), I don't really want to touch this part of the 
code. Sorry.

**Comment by voldikss** [comment]
Never mind.

I also tried looking for the solution. But the code was too difficult for me 😢 

Actually this is not a fatal problem so it doesn't break the experience.

Thanks for the reply. Let me close this issue 😄
